n_prompt: "bad quality, worse quality"
vdm_prompt: "a person"
relight_prompt: "a person, sunset light"
video_path: "input_wan/ffhq/01018.mp4"
bg_source: "TOP"  ## LEFT, RIGHT, BOTTOM, TOP
save_path: "output/wan"

width: 512
height: 512
num_frames: 9
strength: 0.4
gamma: 0.7
num_step: 25
text_guide_scale: 2
seed: 42