n_prompt: "bad quality, worse quality"
vdm_prompt: "a photo of two person near the lake"
relight_prompt: "a photo of two person near the lake, sunset light"
video_path: "input_cog/PPR10K/0_1_0.mp4"
bg_source: "TOP"  ## LEFT, RIGHT, BOTTOM, TOP
save_path: "output/cog/ppr10k"

width: 720
height: 480
strength: 0.4
gamma: 0.7
num_step: 25
text_guide_scale: 2
seed: 42