n_prompt: "bad quality, worse quality"
vdm_prompt: ""
relight_prompt: "a photo, with a warm sunset light, with soft golden and orange hues illuminating the scene. Incorporate realistic gentle shadows and reflections typical of sunset, highlighting textures and creating a serene, captivating ambiance"
video_path: "input_cog/2023-05-06_18.mp4"
bg_source: "TOP"  ## LEFT, RIGHT, BOTTOM, TOP
save_path: "output/cog/ppr10k"

width: 720
height: 480
strength: 0.4
gamma: 0.7
num_step: 25
text_guide_scale: 2
seed: 42