n_prompt: "bad quality, worse quality"
relight_prompt: "a car driving on the street, neon light"
video_path: "input_animatediff/car.mp4"
bg_source: "RIGHT"  ## LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 1024
height: 1024
strength: 0.5
gamma: 0.5
num_step: 25
text_guide_scale: 2
seed: 2060