n_prompt: "bad quality, worse quality"
relight_prompt: "a person, sunset light"
video_path: "input_animatediff/ffhq/01059.mp4"
bg_source: "RIGHT"  ## LEFT, RIGHT, BOTTOM, TOP
save_path: "output/ani"

width: 512
height: 512
strength: 0.5
gamma: 0.5
num_step: 25
text_guide_scale: 2
seed: 2060